# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:


      - name: Advance Security Compliance Action
        uses: GeekMasher/advanced-security-compliance@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          argvs: '--disable-dependabot --disable-secret-scanning --disable-code-scanning'
          policy-path: definition.yml



